server:
  port: 8899

spring:
  application:
    name: assemble-generate-code
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**

logging:
  level:
    com.fengwenyi: debug
    com.baomidou: debug

erwin:
  app:
    name: @project.artifactId@
    version: @project.version@